"""Add AnalysisResult table

Revision ID: 761261ca7076
Revises: 9527a508689e
Create Date: 2026-01-20 19:25:44.173780+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '761261ca7076'
down_revision: Union[str, None] = '9527a508689e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_results',
    sa.Column('result_id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('analyzer_engine', sa.String(), nullable=True),
    sa.Column('static_analysis', sa.JSON(), nullable=True),
    sa.Column('yara_matches', sa.JSON(), nullable=True),
    sa.Column('ai_analysis', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.submission_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('result_id'),
    sa.UniqueConstraint('submission_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analysis_results')
    # ### end Alembic commands ###
