"""add dynamic_analysis column

Revision ID: e1276f3d279f
Revises: 761261ca7076
Create Date: 2026-05-09 17:07:59.970699+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1276f3d279f'
down_revision: Union[str, None] = '761261ca7076'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_results', sa.Column('dynamic_analysis', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis_results', 'dynamic_analysis')
    # ### end Alembic commands ###
